apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.spark.endpoint }}"
  labels:
    {{- include "standalone-spark-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: spark-ui
    - port: 7077
      name: spark-master-port
  selector:
    {{- include "standalone-spark-k8s.selectorLabels" . | nindent 4 }}
